# This file is used for Cargo to discover the Rust package in packages

[workspace]
members = ["packages/kernal"]
default-members = ["packages/kernal"]

# Use resolver v2 so that the configuration in packages/kernal/Cargo.toml is respected
resolver = "2"
